# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.vfs.watch=false

org.gradle.configuration-cache=false
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.2.0+26.2
maven_group=sashwind.mc.mod
archives_base_name=FFCraft
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.154.2+26.2
# libmpv 原生库下载地址（SourceForge 自动选择最优镜像）
mpv_native_url=https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20240922-git-968a433.7z/download
