# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.vfs.watch=false

org.gradle.configuration-cache=false

# Mod Properties (遵循 README 规范：网络api版本号.大更新版本号.BUG修复版本号)
mod_version=1.2.2
maven_group=sashwind.mc.mod
archives_base_name=FFCraft

# Common Fabric Properties
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Version-specific configurations
v26_1_minecraft_version=26.1
v26_1_fabric_version=0.151.0+26.1.2

v26_2_minecraft_version=26.2
v26_2_fabric_version=0.154.2+26.2

# libmpv 原生库下载地址
mpv_native_url=https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20240922-git-968a433.7z/download
